### ISSUE TITLE
این کد درسته؟

### ISSUE THREAD

**Issue by mohammadsec** [0xuf/hamster-glitch#2]
https://github.com/0xuf/hamster-glitch/blob/9d85ad97b2a292409e6b8f2f5127cafde1236294/src/glitch.py#L20

**Comment by kingparsa1010** [comment]
کد درسته ولی باید فایل env. رو ادیت کنی و به جاش auth_token رو بذاری که خود منم نمیدونم auth_token چیه؟ اگه تو میدونی لطفا بهم بگو

**Comment by bug-sniper67** [comment]
https://x.com/ZeroXUF/status/1799525728133820868
من خودم به لینکی نرسیدم طبق کامنت بالا اگر رسیدین اطلاع بدین
